/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as IndexRouteImport } from './routes/index'

const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forecast'
    | '/menu'
    | '/orders'
    | '/performance'
    | '/revenue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forecast' | '/menu' | '/orders' | '/performance' | '/revenue'
  id:
    | '__root__'
    | '/'
    | '/forecast'
    | '/menu'
    | '/orders'
    | '/performance'
    | '/revenue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastRoute: typeof ForecastRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  PerformanceRoute: typeof PerformanceRoute
  RevenueRoute: typeof RevenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastRoute: ForecastRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  PerformanceRoute: PerformanceRoute,
  RevenueRoute: RevenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
