/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevenueYtdRouteImport } from './routes/revenue.ytd'
import { Route as RevenueWeekRouteImport } from './routes/revenue.week'
import { Route as RevenueMtdRouteImport } from './routes/revenue.mtd'

const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueYtdRoute = RevenueYtdRouteImport.update({
  id: '/ytd',
  path: '/ytd',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueWeekRoute = RevenueWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueMtdRoute = RevenueMtdRouteImport.update({
  id: '/mtd',
  path: '/mtd',
  getParentRoute: () => RevenueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue/mtd': typeof RevenueMtdRoute
  '/revenue/week': typeof RevenueWeekRoute
  '/revenue/ytd': typeof RevenueYtdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue/mtd': typeof RevenueMtdRoute
  '/revenue/week': typeof RevenueWeekRoute
  '/revenue/ytd': typeof RevenueYtdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue/mtd': typeof RevenueMtdRoute
  '/revenue/week': typeof RevenueWeekRoute
  '/revenue/ytd': typeof RevenueYtdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forecast'
    | '/menu'
    | '/orders'
    | '/performance'
    | '/revenue'
    | '/revenue/mtd'
    | '/revenue/week'
    | '/revenue/ytd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forecast'
    | '/menu'
    | '/orders'
    | '/performance'
    | '/revenue'
    | '/revenue/mtd'
    | '/revenue/week'
    | '/revenue/ytd'
  id:
    | '__root__'
    | '/'
    | '/forecast'
    | '/menu'
    | '/orders'
    | '/performance'
    | '/revenue'
    | '/revenue/mtd'
    | '/revenue/week'
    | '/revenue/ytd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastRoute: typeof ForecastRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  PerformanceRoute: typeof PerformanceRoute
  RevenueRoute: typeof RevenueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue/ytd': {
      id: '/revenue/ytd'
      path: '/ytd'
      fullPath: '/revenue/ytd'
      preLoaderRoute: typeof RevenueYtdRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/week': {
      id: '/revenue/week'
      path: '/week'
      fullPath: '/revenue/week'
      preLoaderRoute: typeof RevenueWeekRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/mtd': {
      id: '/revenue/mtd'
      path: '/mtd'
      fullPath: '/revenue/mtd'
      preLoaderRoute: typeof RevenueMtdRouteImport
      parentRoute: typeof RevenueRoute
    }
  }
}

interface RevenueRouteChildren {
  RevenueMtdRoute: typeof RevenueMtdRoute
  RevenueWeekRoute: typeof RevenueWeekRoute
  RevenueYtdRoute: typeof RevenueYtdRoute
}

const RevenueRouteChildren: RevenueRouteChildren = {
  RevenueMtdRoute: RevenueMtdRoute,
  RevenueWeekRoute: RevenueWeekRoute,
  RevenueYtdRoute: RevenueYtdRoute,
}

const RevenueRouteWithChildren =
  RevenueRoute._addFileChildren(RevenueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastRoute: ForecastRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  PerformanceRoute: PerformanceRoute,
  RevenueRoute: RevenueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
